[package]
name = "xorctl"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.31.4"
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros", "signal"] }
tokio-cron-scheduler = "*"
