name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: xorctl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            target: x86_64-unknown-linux-musl

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
  
      - name: Build
        run: cargo build --release --verbose

